name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic}
          - {ROS_DISTRO: noetic}
    env:
      CATKIN_LINT: 'true'
      ROSDEP_SKIP_KEYS: 'live555'
      AFTER_INSTALL_TARGET_DEPENDENCIES: 'apt-get install -y liblivemedia-dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 'ros-industrial/industrial_ci@0.10.0'
        env: ${{ matrix.env }}
